# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Michal Lyskawinski
tagline:          "Michal Lyskawinski's website"
description:      "Hi, I am Michal! I build ML apps to tackle complex problems with a big business impact."
url:              https://lyskawinski.com

author:
  name:           'Michal Lyskawinski'
  url:            https://twitter.com/michallys


# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/michalos88/michalos88.github.io
