# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Michal Lyskawinski
tagline:          'A Jekyll theme'
description:      "Hi, I'm Michael. I like building things. I am a <a href='http://jekyllrb.com' target='_blank'>Stevens</a> CS graduate and the co-founder and Bellman Labs."
url:              http://lyskawinski.com

author:
  name:           'Michal Lyskawinski'
  url:            https://twitter.com/mdo


# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/michalos88/michalos88.github.io
