# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Michal Lyskawinski
tagline:          'A Jekyll theme'
description:      "Hi, I'm Michael. I like building things. I am a <a href='http://jekyllrb.com' target='_blank'>Stevens</a> CS graduate and the co-founder and Bellman Labs. Before Arthena I was at Matroid, Planet, Planetary Resources, Facebook, and SEDS."
url:              http://lyskawinski.com
baseurl:          /

author:
  name:           'Michal Lyskawinski'
  url:            https://twitter.com/mdo


paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/michalos88/michalos88.github.io
